site_name: Artificial Intelligence
nav:
        - Home: index.md
        - '1. Fundamentos da Inteligência Artificial': ia/01_fundamentos.md
        - '2. Aprendizado de Máquina': ia/02_aprendizado.md
        - '3. Deep Learning': ia/03_deep_learning.md
        - 'Visão Computacional':
                - 'Part 1: Basics': ia/05_Computer_Vision/basics.md
                - 'Part 2: Intermediary': ia/05_Computer_Vision/intermediary.md
                - 'Part 3: Advanced':
                        - '5.1 Intro': ia/05_Computer_Vision/intro.md
                        - '5.2 SSD': ia/05_Computer_Vision/ssd.md
        - '6. Processamento de Linguagem Natural': ia/05_pln.md
        - '7. Robótica e Sistemas Autônomos': ia/06_sa.md
        - About: about.md
theme: readthedocs
